### ISSUE TITLE
Contact Form Styling

### ISSUE THREAD

**Issue by justaguyinaz** [darklow/exposure-theme-issues#1]
If this is a bug please specify versions you're using first.

Koken version: 0.22.21 
PHP Version: (if related to PHP errors)

Issue: This is a request for Integrating styling for built-in Koken contact form.
------

**Comment by justaguyinaz** [comment]
I added the following to the bottom of exposure.css for now. Seems to be okay, but would love to see what you might be able to better integrate.

/* Form Styling */

form { max-width: 66%; margin: 0 auto 100px auto; background-color: #fafafa; border: 1px solid #d9d9d9; border-radius: 4px; padding: 5px 15px 15px 15px; }

label { margin: 5px 0; }

button { margin-top: 10px; display: inline-block; padding: 6px 12px; font-weight: 400; cursor: pointer; color: #555; background-color: #fff; border: 1px solid #ccc; border-radius: 4px; width: 100px; text-transform: uppercase; font-family: "Montserrat", sans-serif; letter-spacing: 1px; font-size: 0.75rem; font-weight: bold;}

button:hover { color: #000; }

input[type="text"], input[type="password"], input[type="date"], input[type="datetime"], input[type="datetime-local"], input[type="month"], input[type="week"], input[type="email"], input[type="number"], input[type="search"], input[type="tel"], input[type="time"], input[type="url"], input[type="color"], textarea { display: block; width: 100%; height: 34px; padding: 6px 12px; color: #555; border: 1px solid #ccc; border-radius: 4px;}

textarea[rows] { height: 200px; }

![contact_-_matthew_barker_photography](https://cloud.githubusercontent.com/assets/188607/26459088/fd777388-417d-11e7-80ad-74748b76ab4c.png)

**Comment by darklow** [comment]
Thanks. I am using latest bootstrap v4.alpha for main layout. I'll uncomment and tweak form style in next version.

**Comment by justaguyinaz** [comment]
Sounds good; thanks for a great theme and quick responses!

**Comment by darklow** [comment]
Feel free to share your Koken site when it's live! I am planning to add showcase to website.

**Comment by darklow** [comment]
I just released new version with Contact form style and Mailchimp base url config param fix. You should already have an automatic email in your inbox. This is how I styled contact form, I think simplicity and straight corners are more appropriate for this theme:

![image](https://user-images.githubusercontent.com/445304/27509788-beeb4e70-5904-11e7-997f-43de5b2747c0.png)
