### ISSUE TITLE
Pulse Integration

### ISSUE THREAD

**Issue by justaguyinaz** [darklow/exposure-theme-issues#2]
If this is a bug please specify versions you're using first.

Koken version: 0.22.21 
PHP Version: (if related to PHP errors)

Issue: This is a request to integrate the built-in Pulse slideshow with this theme.
------

**Comment by darklow** [comment]
I just tried adding Presentation to About page and it does load Pulse slideshows correctly, have you tried it?

**Comment by justaguyinaz** [comment]
Sorry - I might just be ignorant on how to do that as I'm new to Koken as well as the theme. I'll play around with it a bit more, but didn't see any kind of menu for the slideshow as described with the two Pulse plugins Koken's site offers.

**Comment by justaguyinaz** [comment]
I am just not seeing any options for Pulse configuration when adding a slideshow anywhere. Looking for something like the example here:
https://store.koken.me/plugins/pulse-transition-pack/guide/1
or here:
https://store.koken.me/plugins/pulse-playback-timer/guide/1

**Comment by justaguyinaz** [comment]
Totally missed where all of that was at... Sorry for my confusion. Consider this a non-issue.

http://help.koken.me/customer/portal/articles/1209871-style-slideshows-in-a-theme
